version: 2
jobs:
  build:
    working_directory: /go/src/github.com/sk88ks/flow
    docker:
      - image: circleci/golang:1.9.1
    steps:
      - checkout
      - run: make setup
      - run: make cover 
      - run: bash <(curl -s https://codecov.io/bash)
